# Generated by Django 5.1.4 on 2026-04-29 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['type_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('mission', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('github_repo', models.URLField(blank=True)),
                ('jira_link', models.URLField(blank=True)),
                ('confluence_link', models.URLField(blank=True)),
                ('slack_channel', models.CharField(blank=True, max_length=80)),
                ('teams_channel', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('standup_time', models.CharField(blank=True, max_length=40)),
                ('agile_practices', models.CharField(blank=True, max_length=120)),
                ('num_concurrent_projects', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='organisation.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_managed', to=settings.AUTH_USER_MODEL)),
                ('team_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='teams.teamtype')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'department')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Engineer', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Staff',
                'ordering': ['team', 'user'],
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('dependency_type', models.CharField(choices=[('API', 'API consumer'), ('DATA', 'Data feed'), ('PLATFORM', 'Platform'), ('OTHER', 'Other')], default='API', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('downstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_links', to='teams.team')),
                ('upstream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_links', to='teams.team')),
            ],
            options={
                'verbose_name_plural': 'Team dependencies',
                'constraints': [models.CheckConstraint(condition=models.Q(('upstream', models.F('downstream')), _negated=True), name='no_self_dependency')],
                'unique_together': {('upstream', 'downstream')},
            },
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed', models.DateField()),
                ('stepped_down', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lead_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-appointed'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('stepped_down__isnull', True)), fields=('team',), name='one_active_lead_per_team')],
            },
        ),
        migrations.CreateModel(
            name='TeamSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('BASIC', 'Basic'), ('INTERMEDIATE', 'Intermediate'), ('EXPERT', 'Expert')], default='INTERMEDIATE', max_length=20)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_skills', to='teams.skill')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_skills', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'skill')},
            },
        ),
    ]
